RUN_TESTS = FALSE 
library(varhandle)
# ----------------------------------------------------------------------------------------

# Constants:

# ----------------------------------------------------------------------------------------

RIGHT_CENSORING = 0

POSITIVE = 1
HOME = 2
MILD_OR_MODERATE = 3
SEVERE = 4
CRITICAL = 5
DECEASED = 6
DISCHARGED = 7

# "non-states":
MILD = 8
MODERATE = 9
SEVERE_OR_CRITICAL = 10 # for reduced covariates models

TERMINAL_STATES = c(HOME, DECEASED) # DISCHARGED is not always a terminal state!
EXCLUDED_TRANSITIONS = list(c(DISCHARGED, CRITICAL))

map_state_name_to_integer_code = list(
  "home" = HOME,
  "MnM" = MILD_OR_MODERATE,
  "severe" = SEVERE,
  "critical" = CRITICAL,
  "death" = DECEASED,
  "Out" = DISCHARGED,
  "mild" = MILD,
  "moderate" = MODERATE,
  "severe_or_critical" = SEVERE_OR_CRITICAL
)

MALE = 1
FEMALE = 0


# ----------------------------------------------------------------------------------------

# format data for fits:

# ----------------------------------------------------------------------------------------

format_positive_to_hospitalization_df = function(pos_df, use_sector=TRUE) {
  # construct covariates:
  
  if (use_sector) {
    pos_covariates_df = as.data.frame(model.matrix(~age*gender + age*sector + gender*sector, pos_df))  
  } else {
    pos_covariates_df = as.data.frame(model.matrix(~age*gender, pos_df))
  }
  covariate_names = tail(names(pos_covariates_df), n=-1) # exclude intercept generated by model.matrix
  
  # non-covariate columns needed:
  non_covariate_column_names = c('type0', 'days_from_positive_to_hosp', 'first_positive_test_date')
  
  # combine:
  pos_df = cbind(pos_covariates_df[,covariate_names], pos_df[,non_covariate_column_names])
  
  # convert 0 -> home
  pos_df$type0 = ifelse(pos_df$type0 == 0, "home", pos_df$type0)
  
  # exclude 0 days_from_positive_to_hosp subjects:
  # nrow(pos_df[pos_df$days_from_positive_to_hosp==0,])
  # pos_df = pos_df[!pos_df$days_from_positive_to_hosp==0,]
  
  pos_df$type0 = sapply(pos_df$type0, function(state_name) map_state_name_to_integer_code[[state_name]])
  
  # round days_from_positive_to_hosp:
  pos_df$days_from_positive_to_hosp = round(pos_df$days_from_positive_to_hosp)
  
  return(list(
    "pos_df" = pos_df,
    "covariate_names" = covariate_names
  ))
}


construct_msm_dataset_from_hospitalized_onward_df = function(hosp_df, use_reduced_covariates=FALSE, critical_state_at_hospitalization_only=FALSE) {
  
  # these 0 values are only used for initialization 
  # values for each state are updated according to the transition function when fitting the model.
  hosp_df$was_critical = 0
  hosp_df$was_severe = 0
  hosp_df$cumulative_time = 0
  hosp_df$state_at_hospitalization = hosp_df$Ntype0 # mild and moderate are separate states here
  
  if (!use_reduced_covariates) {
    initial_covariates_df = as.data.frame(model.matrix(~age*sex + age*state_at_hospitalization + age*cumulative_time + age*was_severe + age*was_critical, hosp_df))  
  } else {
    if (!critical_state_at_hospitalization_only) {
      hosp_df$state_at_hospitalization = ifelse(hosp_df$state_at_hospitalization %in% c("severe", "critical"), "severe_or_critical", hosp_df$state_at_hospitalization)

      # allow all zeros input to default to both critical and severe:
      hosp_df$state_at_hospitalization = factor(hosp_df$state_at_hospitalization, levels = c("severe_or_critical", "mild", "moderate"))
      initial_covariates_df = as.data.frame(model.matrix(~age*sex + age*state_at_hospitalization + age*cumulative_time + age*was_severe, hosp_df))
    } else {
      hosp_df$not_hospitalized_critical = as.integer(!(hosp_df$state_at_hospitalization == "critical"))
      initial_covariates_df = as.data.frame(model.matrix(~age*sex + age*not_hospitalized_critical + age*cumulative_time + age*was_severe, hosp_df))
    }
  }
  
  covariate_names = tail(names(initial_covariates_df), n=-1) # exclude intercept generated from model.matrix
  non_covariate_column_names = c('source_state', 'target_state', 'tstop', 'tstart', 'id', 'first_date')
  
  # combined df:
  hosp_df = cbind(initial_covariates_df[,covariate_names], hosp_df[,non_covariate_column_names])
  
  
  NO_STATE_CHANGE = 0
  
  hosp_df$source_state = sapply(hosp_df$source_state, function(s) as.integer(map_state_name_to_integer_code[[s]]) )
  hosp_df$target_state = sapply(hosp_df$target_state, function(s) {
    if (s == NO_STATE_CHANGE){
      return(NO_STATE_CHANGE)
    } else {
      if (check.numeric(s)){
          if (as.numeric(s) == NO_STATE_CHANGE){
            return(NO_STATE_CHANGE)
          }
        }
      return(as.integer(map_state_name_to_integer_code[[s]]))
    }
  } )
  
  
  construct_one_object = function(id) {
    
    patient_data = hosp_df[hosp_df$id == id,]
    
    # construct the series of states visited:
    states = c(patient_data$source_state)
    last_state = tail(patient_data$target_state, n=1)
    if (last_state != NO_STATE_CHANGE) states = c(states, last_state)
    
    time_at_each_state = patient_data$tstop - patient_data$tstart
    
    # covariates at time of hospitalization:
    covariates = as.numeric(patient_data[1, covariate_names])
    
    object = list(
      covariates = covariates,
      states = states,
      time_at_each_state = time_at_each_state,
      id = id,
      
      date_of_hospitalization = as.Date(patient_data$first_date[1])
    )
    
    return(object)
  }
  
  
  dataset = lapply(unique(hosp_df$id), function(id) construct_one_object(id))
  
  return(list(
    covariate_names = covariate_names,
    dataset = dataset
  ))
}



# ----------------------------------------------------------------------------------------

# constructing covariates at "positive":

# ----------------------------------------------------------------------------------------

AGE_COVARIATE_IDX = 1
IS_MALE_COVARIATE_IDX = 2


construct_positive_covariates = function(age,
                                         is_male,
                                         sector) {
  

  covariates = rep(0, 12)
  
  covariates[1] =  age # age
  covariates[2] =  is_male # gendermale
  covariates[3] =  sector == "haredim" # sectorharedim
  covariates[4] =  sector == "mixed" # sectormixed
  covariates[5] =  sector == "rest" # sectorrest
  covariates[6] =  age * is_male # age:gendermale
  covariates[7] =  age * (sector == "haredim") # age:sectorharedim
  covariates[8] =  age * (sector == "mixed") # age:sectormixed
  covariates[9] =  age * (sector == "rest") # age:sectorrest
  covariates[10] = is_male * (sector == "haredim") # gendermale:sectorharedim
  covariates[11] = is_male * (sector == "mixed") # gendermale:sectormixed
  covariates[12] = is_male * (sector == "rest") # gendermale:sectorrest

  return(covariates)
}

# --- TEST ---:
if (RUN_TESTS) {
  original_pos_df = read.csv('data/fit_data/01-positive_to_hospitalized.csv', row.names = 1)
  original_pos_df$sector = ifelse(pos_df$sector == "unknown", yes = "rest", no = pos_df$sector)

  
  . = format_positive_to_hospitalization_df(original_pos_df)
  formatted_pos_df = .$pos_df
  covariate_names = .$covariate_names
  covariates_X = formatted_pos_df[,covariate_names]
  
  test_construct_positive_covariates = function(idx) {
    stopifnot(construct_positive_covariates(
                original_pos_df$age[idx],
                original_pos_df$gender[idx] == 'male',
                original_pos_df$sector[idx]
              ) == covariates_X[idx,])
  }
  
  for (idx in c(1:100)) {
    test_construct_positive_covariates(idx)  
  }
  print("PASSED")
}

# ----------------------------------------------------------------------------------------

# constructing covariates for hospitalized (and onward) patient:

# ----------------------------------------------------------------------------------------

MILD_COVARIATE_IDX = 3
MODERATE_COVARIATE_IDX = 4
SEVERE_COVARIATE_IDX = 5
CUMULATIVE_TIME_COVARIATE_IDX = 6
WAS_SEVERE_COVARIATE_IDX = 7
WAS_CRITICAL_COVARIATE_IDX = 8

construct_hospitalized_patient_covariates = function(age, 
                                                     is_male, 
                                                     state_at_hospitalization, 
                                                     cumulative_time_since_hospitalization,
                                                     was_severe, # in some state BEFORE current state
                                                     was_critical # in some state BEFORE current state
                                                     ) {
  
  covariates = rep(0, 15)
  
  covariates[1] =  age
  covariates[2] =  is_male # sexmale
  covariates[3] =  state_at_hospitalization == MILD # state_at_hospitalizationmild
  covariates[4] =  state_at_hospitalization == MODERATE # state_at_hospitalizationmoderate
  covariates[5] =  state_at_hospitalization == SEVERE # state_at_hospitalizationsevere
  covariates[6] =  cumulative_time_since_hospitalization # cumulative_time
  covariates[7] =  was_severe # was_severe
  covariates[8] =  was_critical # was_critical
  covariates[9] =  age * is_male # age:sexmale
  covariates[10] = age * (state_at_hospitalization == MILD) # age:state_at_hospitalizationmild
  covariates[11] = age * (state_at_hospitalization == MODERATE) # age:state_at_hospitalizationmoderate
  covariates[12] = age * (state_at_hospitalization == SEVERE) # age:state_at_hospitalizationsevere
  covariates[13] = age * cumulative_time_since_hospitalization # age:cumulative_time
  covariates[14] = age * was_severe # age:was_severe
  covariates[15] = age * was_critical # age:was_critical
  
  return(covariates)
}

get_state_at_hospitalization = function(covariates) {
  if (covariates[MILD_COVARIATE_IDX]) return(MILD)
  if (covariates[MODERATE_COVARIATE_IDX]) return(MODERATE)
  if (covariates[SEVERE_COVARIATE_IDX]) return(SEVERE)
  return(CRITICAL)
}

# --- TEST ---:
RUN_TESTS == FALSE
if (RUN_TESTS) {
  hosp_df = read.csv('data/fit_data/02-hospitalized_onward.csv')
  
  . = construct_msm_dataset_from_hospitalized_onward_df(hosp_df)
  dataset = .$dataset
  covariate_names = .$covariate_names
  
  test_construct_hospitalized_patient_covariates = function(hosp_row_idx, dataset_obj_idx) {
    stopifnot(construct_hospitalized_patient_covariates(
                hosp_df$age[hosp_row_idx],
                hosp_df$sex[hosp_row_idx] == 'male',
                map_state_name_to_integer_code[hosp_df$Ntype0[hosp_row_idx]],
                0,
                0,
                0
              ) == dataset[[dataset_obj_idx]]$covariates)
  }
  
  hosp_df$row_number = 1:nrow(hosp_df)
  first_row_per_patient = hosp_df[hosp_df$id != c(100, head(hosp_df$id, -1)), ]
  
  ids = first_row_per_patient$id
  row_numbers = first_row_per_patient$row_number
  
  for (i in 1:100) {
    # print(paste(row_numbers[i], ids[i]))
    test_construct_hospitalized_patient_covariates(row_numbers[i], ids[i])  
  }
  
  stopifnot(get_state_at_hospitalization(dataset[[1]]$covariates) == MILD)
  stopifnot(get_state_at_hospitalization(dataset[[2]]$covariates) == MODERATE)
  stopifnot(get_state_at_hospitalization(dataset[[16]]$covariates) == SEVERE)
  stopifnot(get_state_at_hospitalization(dataset[[30]]$covariates) == CRITICAL)
}


# ----------------------------------------------------------------------------------------

# constructing REDUCED covariates for hospitalized (and onward) patient:

# ----------------------------------------------------------------------------------------

REDUCED_AGE_COVARIATE_IDX = 1
REDUCED_IS_MALE_COVARIATE_IDX = 2
REDUCED_MILD_COVARIATE_IDX = 3
REDUCED_MODERATE_COVARIATE_IDX = 4
REDUCED_CUMULATIVE_TIME_COVARIATE_IDX = 5
REDUCED_WAS_SEVERE_COVARIATE_IDX = 6
REDUCED_AGE_IS_MALE_INTERACTION_IDX = 7
REDUCED_AGE_MILD_INTERACTION_IDX = 8
REDUCED_AGE_MODERATE_INTERACTION_IDX = 9
REDUCED_AGE_CUMULATIVE_TIME_INTERACTION_IDX = 10
REDUCED_AGE_WAS_SEVERE_INTERACTION_IDX = 11
  
construct_hospitalized_patient_REDUCED_covariates = function(age,
                                                             is_male,
                                                             state_at_hospitalization, # includes MILD, MODERATE and SEVERE_OR_CRITICAL
                                                             cumulative_time_since_hospitalization,
                                                             was_severe # in some state BEFORE current state
                                                             ) {
  
  covariates = rep(0, 11)
  
  covariates[1] =  age # age
  covariates[2] =  is_male # sexmale
  covariates[3] =  (state_at_hospitalization == MILD) # state_at_hospitalizationmild
  covariates[4] =  (state_at_hospitalization == MODERATE) # state_at_hospitalizationmoderate
  covariates[5] =  cumulative_time_since_hospitalization # cumulative_time
  covariates[6] =  was_severe #was_severe
  covariates[7] =  (age * is_male) #age:sexmale
  covariates[8] =  (age * (state_at_hospitalization == MILD) ) # age:state_at_hospitalizationmild
  covariates[9] =  (age * (state_at_hospitalization == MODERATE) ) # age:state_at_hospitalizationmoderate
  covariates[10] = (age * cumulative_time_since_hospitalization ) # age:cumulative_time
  covariates[11] = (age * was_severe) # age:was_severe

  return(covariates)
}

get_REDUCED_state_at_hospitalization = function(covariates) {
  if (covariates[REDUCED_MILD_COVARIATE_IDX]) return(MILD)
  if (covariates[REDUCED_MODERATE_COVARIATE_IDX]) return(MODERATE)
  return(SEVERE_OR_CRITICAL)
}

RUN_TESTS=FALSE

# --- TEST ---:
if (RUN_TESTS) {
  hosp_df = read.csv('data/02-hospitalized_onward.csv')
  
  
  . = construct_msm_dataset_from_hospitalized_onward_df(hosp_df, use_reduced_covariates = TRUE)
  dataset = .$dataset
  covariate_names = .$covariate_names

  hosp_df$Ntype0 = ifelse(hosp_df$Ntype0 %in% c("severe", "critical"), "severe_or_critical", hosp_df$Ntype0)
  
  test_construct_hospitalized_patient_covariates = function(hosp_row_idx, dataset_obj_idx) {
    
    
    constructed_covariates = construct_hospitalized_patient_REDUCED_covariates(
                              hosp_df$age[hosp_row_idx],
                              hosp_df$sex[hosp_row_idx] == 'male',
                              map_state_name_to_integer_code[hosp_df$Ntype0[hosp_row_idx]],
                              0,
                              0
                            )
    dataset_covariates = dataset[[dataset_obj_idx]]$covariates
    
    # print(constructed_covariates)
    # print(dataset_covariates)

    stopifnot(constructed_covariates == dataset_covariates)
  }

  hosp_df$row_number = 1:nrow(hosp_df)
  first_row_per_patient = hosp_df[hosp_df$id != c(100, head(hosp_df$id, -1)), ]
  
  ids = first_row_per_patient$id
  row_numbers = first_row_per_patient$row_number
  
  for (i in 1:100) {
    # print(paste(row_numbers[i], ids[i]))
    test_construct_hospitalized_patient_covariates(row_numbers[i], ids[i])  
  }

  stopifnot(get_REDUCED_state_at_hospitalization(dataset[[1]]$covariates) == MILD)
  stopifnot(get_REDUCED_state_at_hospitalization(dataset[[2]]$covariates) == MODERATE)
  stopifnot(get_REDUCED_state_at_hospitalization(dataset[[16]]$covariates) == SEVERE_OR_CRITICAL)
  stopifnot(get_REDUCED_state_at_hospitalization(dataset[[30]]$covariates) == SEVERE_OR_CRITICAL)
}

# ----------------------------------------------------------------------------------------

# constructing FURTHER_REDUCED covariates for hospitalized (and onward) patient:

# ----------------------------------------------------------------------------------------

FURTHER_REDUCED_AGE_COVARIATE_IDX = 1 # age
FURTHER_REDUCED_IS_MALE_COVARIATE_IDX = 2 # sexmale
FURTHER_REDUCED_NOT_HOSPITALIZED_CRITICAL_COVARIATE_IDX = 3 # not_hospitalized_critical
FURTHER_REDUCED_CUMULATIVE_TIME_COVARIATE_IDX = 4 # cumulative_time
FURTHER_REDUCED_WAS_SEVERE_COVARIATE_IDX = 5 # was_severe
FURTHER_REDUCED_AGE_IS_MALE_INTERACTION_IDX = 6 # age:sexmale
FURTHER_REDUCED_AGE_NOT_HOSPITALIZED_CRITICAL_INTERACTION_IDX = 7 # age:not_hospitalized_critical
FURTHER_REDUCED_AGE_CUMULATIVE_TIME_INTERACTION_IDX = 8 # age:cumulative_time
FURTHER_REDUCED_AGE_WAS_SEVERE_INTERACTION_IDX = 9 # age:was_severe

construct_hospitalized_patient_FURTHER_REDUCED_covariates = function(age,
                                                             is_male,
                                                             not_hospitalized_critical,
                                                             cumulative_time_since_hospitalization,
                                                             was_severe # in some state BEFORE current state
) {

  covariates = rep(0, 9)

  covariates[1] =  age # age
  covariates[2] =  is_male # sexmale
  covariates[3] =  not_hospitalized_critical # not_hospitalized_critical
  covariates[4] =  cumulative_time_since_hospitalization # cumulative_time
  covariates[5] =  was_severe #was_severe
  covariates[6] =  (age * is_male) #age:sexmale
  covariates[7] =  (age * not_hospitalized_critical) # age:not_hospitalized_critical
  covariates[8] =  (age * cumulative_time_since_hospitalization ) # age:cumulative_time
  covariates[9] =  (age * was_severe) # age:was_severe

  return(covariates)
}


RUN_TESTS=FALSE
# --- TEST ---:
if (RUN_TESTS) {
  hosp_df = read.csv('data/fit_data/02-hospitalized_onward.csv')


  . = construct_msm_dataset_from_hospitalized_onward_df(hosp_df, use_reduced_covariates = TRUE, critical_state_at_hospitalization_only = TRUE)
  dataset = .$dataset
  covariate_names = .$covariate_names

  hosp_df$not_hospitalized_critical = hosp_df$Ntype0 != "critical"

  test_construct_hospitalized_patient_covariates = function(hosp_row_idx, dataset_obj_idx) {


    constructed_covariates = construct_hospitalized_patient_FURTHER_REDUCED_covariates(
      hosp_df$age[hosp_row_idx],
      hosp_df$sex[hosp_row_idx] == 'male',
      hosp_df$not_hospitalized_critical[hosp_row_idx],
      0,
      0
    )
    dataset_covariates = dataset[[dataset_obj_idx]]$covariates

    # print(constructed_covariates)
    # print(dataset_covariates)

    stopifnot(constructed_covariates == dataset_covariates)
  }

  hosp_df$row_number = 1:nrow(hosp_df)
  first_row_per_patient = hosp_df[hosp_df$id != c(100, head(hosp_df$id, -1)), ]

  ids = first_row_per_patient$id
  row_numbers = first_row_per_patient$row_number

  for (i in 1:100) {
    # print(paste(row_numbers[i], ids[i]))
    test_construct_hospitalized_patient_covariates(row_numbers[i], ids[i])
  }
  print('PASSED')
}




# ----------------------------------------------------------------------------------------

# Debug Tools:

# ----------------------------------------------------------------------------------------

# unnormalized (taking larger current_time should lead to probabilities not summing to one)
print_next_state_probabilities = function(cr_model, covariates, current_time) {
  ms_model = MultiStateModel()
  ms_model$time_is_discrete = TRUE
  probs = c()
  for (state_name in names(map_state_name_to_integer_code) ) {
    
    next_state = map_state_name_to_integer_code[[state_name]]
    
    if (! next_state %in% cr_model$failure_types) next
    
    p = ms_model$probability_for_next_state(next_state = next_state, 
                                            competing_risks_model = cr_model, 
                                            sample_covariates = covariates, 
                                            t_entry_to_current_state = current_time)  
    
    probs = c(probs, p)
    print(paste(state_name, p))
  }
  
  print(paste("--- sum of probabilities: ", sum(probs), " ---"))
  
  
  return(sum(probs))
}